schemaVersion: "2.0.0"
  
commandTests:
  - name: "pylint version"
    command: "pylint"
    args: ["-v"]
    expectedOutput: ["4.18.1"]

fileExistenceTests:
- name: 'linter script'
  path: '/eslint.sh'
  shouldExist: true
  permissions: '-rwxr-xr-x'
