schemaVersion: "2.0.0"

commandTests:
  - name: "eslint version"
    command: "/linter/node_modules/.bin/eslint"
    args: ["-v"]
    expectedOutput: ["4.18.1"]

fileExistenceTests:
  - name: 'linter script'
    path: '/linter/eslint.sh'
    shouldExist: true
    permissions: '-rwxrwxr-x'
