schemaVersion: "2.0.0"

commandTests:
  - name: "sass-lint version"
    command: "sass-lint"
    args: ["--version"]
    expectedOutput: ["1.12.1"]

fileExistenceTests:
  - name: 'linter script'
    path: '/sass-lint.sh'
    shouldExist: true
    permissions: '-rwxrwxr-x'
