schemaVersion: "2.0.0"
  
commandTests:
  - name: "pylint version"
    command: "pylint"
    args: ["--version"]
    expectedOutput: ["1.8.2"]

fileExistenceTests:
- name: 'linter script'
  path: '/pylint.sh'
  shouldExist: true
  permissions: '-rwxrwxr-x'
