schemaVersion: "2.0.0"

commandTests:
  - name: "rubocop version"
    command: "rubocop"
    args: ["-v"]
    expectedOutput: ["0.64.0"]

fileExistenceTests:
  - name: 'linter script'
    path: '/rubocop.sh'
    shouldExist: true
    permissions: '-rwxrwxr-x'
