schemaVersion: "2.0.0"

commandTests:
  - name: "yamllint version"
    command: "yamllint"
    args: ["--version"]
    expectedOutput: ["1.11.1"]

fileExistenceTests:
- name: 'linter script'
  path: '/yamllint.sh'
  shouldExist: true
  permissions: '-rwxrwxr-x'
