schemaVersion: "2.0.0"

commandTests:
  - name: "stylelint version"
    command: "/linter/node_modules/.bin/stylelint"
    args: ["--version"]
    expectedOutput: ["9.1.1"]

fileExistenceTests:
  - name: 'linter script'
    path: '/linter/stylelint.sh'
    shouldExist: true
    permissions: '-rwxrwxr-x'
