schemaVersion: "2.0.0"
  
commandTests:
  - name: "haml-lint version"
    command: "haml-lint"
    args: ["-v"]
    expectedOutput: ["0.27.0"]

fileExistenceTests:
- name: 'linter script'
  path: '/haml-lint.sh'
  shouldExist: true
  permissions: '-rwxr-xr-x'
