schemaVersion: "2.0.0"
  
commandTests:
  - name: "coffeelint version"
    command: "coffeelint"
    args: ["-v"]
    expectedOutput: ["2.0.6"]

fileExistenceTests:
- name: 'linter script'
  path: '/coffeelint.sh'
  shouldExist: true
  permissions: '-rwxrwxr-x'
