schemaVersion: "2.0.0"

commandTests:
  - name: "markdownlint version"
    command: "/linter/node_modules/.bin/remark"
    args: ["-v"]
    expectedOutput: ["5.0.0"]

fileExistenceTests:
- name: 'linter script'
  path: '/linter/remark.sh'
  shouldExist: true
  permissions: '-rwxrwxr-x'
